apiVersion: v1
kind: Namespace
metadata:
  name: certbot
  labels:
    name: certbot
---
apiVersion: batch/v1
kind: Job
metadata:
  name: certbot-job
  namespace: certbot
spec:
  template:
    spec:
      containers:
      - name: certbot
        image: certbot/certbot
        args:
        - certonly
        - --standalone
        - -d
        - hellion-local.duckdns.org
        - --email
        - painwoe@gmail.com
        - --agree-tos
        - --non-interactive
        volumeMounts:
        - name: certs
          mountPath: /etc/letsencrypt
      restartPolicy: OnFailure
      volumes:
      - name: certs
        persistentVolumeClaim:
          claimName: certs-pvc