apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-renew
  namespace: certbot
spec:
  schedule: "0 0 * * *"  # This will run the job every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: certbot
            image: certbot/certbot
            args:
            - renew
            volumeMounts:
            - name: certs
              mountPath: /etc/letsencrypt
          restartPolicy: OnFailure
          volumes:
          - name: certs
            persistentVolumeClaim:
              claimName: certs-pvc  # Ensure you have a PVC named certs-pvc for storing certificates