apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:v2.5.0
        ports:
        - containerPort: 8080
        - containerPort: 443
        args: ["argocd-server"]
        env:
        - name: ARGOCD_SERVER
          value: "argocd-server"
        - name: ARGOCD_SERVER_REPO_SERVER
          value: "argocd-repo-server"
        - name: ARGOCD_SERVER_APPLICATION_CONTROLLER
          value: "argocd-application-controller"
        - name: ARGOCD_SERVER_DASHBOARD
          value: "argocd-dashboard"